server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  shutdown: graceful

spring:
  application:
    name: catalog-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/PolarBookshop
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/bookshopdb_catalog
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
    jpa:
      hibernate:
        ddl-auto: validate
#  lifecycle:
#    timeout-per-shutdown-phase: 15s
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh

polar:
  greeting: Welcome to the local book catalog!

file:
  service:
    url: http://localhost:9008

